backend:
  name: git-gateway
  branch: main
  squash_merges: true

local_backend: true
media_folder: '/public/file/cms/'
public_folder: '/file/cms/'

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

i18n:
  structure: multiple_folders
  locales: [ 'de', 'en' ]
  default_locale: 'de'

cms_mixins:
  cms_field_relation: &FIELD_RELATION
    widget: relation
    options_length: 100
    i18n: duplicate
  cms_field_string: &FIELD_STRING
    name: 'string'
    label: 'Kurztext'
    required: true
    widget: string
    i18n: true
  cms_field_text: &FIELD_TEXT
    name: 'text'
    label: 'Text'
    required: true
    widget: text
    i18n: true
  cms_field_id: &FIELD_ID
    <<: *FIELD_STRING
    name: 'id'
    label: 'Id'
    i18n: duplicate
    pattern: [ '^[a-z0-9_]+$', 'Bitte nur Kleinbuchstaben, Zahlen und Underscores verwenden!' ]
    hint: 'Technischer Identifikator, z.B. für die Verwendung in der URL. Bitte nur Kleinbuchstaben, Zahlen und Underscores verwenden, möglichst in Englisch schreiben und darauf achten, dass der Begriff einzigartig ist in seinem Bereich. Beispiel: "eingang_station"'
  cms_field_name: &FIELD_NAME
    <<: *FIELD_STRING
    name: 'name'
    label: 'Name'
    hint: 'Wird als Titel verwendet.'
  cms_field_image: &FIELD_IMAGE
    name: 'image'
    label: 'Bild'
    required: true
    widget: image
    i18n: duplicate
    allow_multiple: false
    choose_url: false

collections:
  - name: 'game_scene'
    label: 'Szenen'
    label_singular: 'Szene'
    i18n: true
    sortable_fields: [ 'name', 'id' ]
    folder: 'content/cms/scene'
    slug: '{{fields.id}}'
    widget: object
    summary: '{{fields.name}} ––– {{fields.id}}'
    format: 'json'
    create: true
    delete: true
    editor:
      preview: false
    fields:
      - *FIELD_ID
      - *FIELD_NAME
      - <<: *FIELD_IMAGE
        name: 'illustration'
        label: 'Illustration Szene'
        media_folder: '/public/image/cms/scene/illustration/'
        public_folder: '/image/cms/scene/illustration/'
      - name: 'dialogue'
        label: 'Dialog-Code'
        widget: code

  - name: 'translation'
    label: 'Übersetzungen'
    label_singular: 'Übersetzung'
    folder: 'content/cms/translation'
    slug: '{{fields.slug}}'
    widget: object
    summary: '{{fields.slug}}'
    format: 'json'
    create: true
    editor:
      preview: false
    fields:
      - name: 'slug'
        label: 'Gruppe'
        i18n: duplicate
        pattern: [ '^[a-z0-9_]+$', 'Bitte nur Kleinbuchstaben, Zahlen und Underscores verwenden!' ]
        hint: 'Thematische Klammer oder Element, in denen die Übersetzungen verwendet werden.'
      - name: 'items'
        label: 'übersetzungen'
        label_singular: 'Übersetzung'
        widget: list
        summary: '{{fields.key}} [DE = "{{fields.value_de}}"]'
        fields:
          - <<: *FIELD_STRING
            name: 'key'
            label: 'Schlüssel'
            i18n: duplicate
            pattern: [ '^([a-z0-9_\.])+$', 'Bitte nur Kleinbuchstaben, Underscores und Punkte verwenden!' ]
            hint: 'Identifikator der Übersetzung, kann aus mehreren Untergruppen bestehen. Beispiel: "button.label"'
          - name: 'value_de'
            label: 'Übersetzung DE'
            widget: string
            hint: 'Übersetzung (de)'
          - name: 'value_en'
            label: 'Übersetzung EN'
            widget: string
            required: false
            hint: 'Übersetzung (en)'
